djangocms_newsletter/models.py
"""Models for emencia.django.newsletter"""
from smtplib import SMTP
from smtplib import SMTPHeloError
from datetime import datetime
from datetime import timedelta

from django.db import models
from django.utils.encoding import smart_str
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Group
from django.utils.encoding import force_unicode

from tagging.fields import TagField
from emencia.django.newsletter.managers import ContactManager
from emencia.django.newsletter.settings import BASE_PATH
from emencia.django.newsletter.settings import MAILER_HARD_LIMIT
from emencia.django.newsletter.settings import DEFAULT_HEADER_REPLY
from emencia.django.newsletter.settings import DEFAULT_HEADER_SENDER
from emencia.django.newsletter.utils.vcard import vcard_contact_export

# Patch for Python < 2.6
try:
    getattr(SMTP, 'ehlo_or_helo_if_needed')
except AttributeError:
    def ehlo_or_helo_if_needed(self):
        if self.helo_resp is None and self.ehlo_resp is None:
            if not (200 <= self.ehlo()[0] <= 299):
                (code, resp) = self.helo()
                if not (200 <= code <= 299):
                    raise SMTPHeloError(code, resp)
    SMTP.ehlo_or_helo_if_needed = ehlo_or_helo_if_needed


class SMTPServer(models.Model):
    """Configuration of a SMTP server"""
    name = models.CharField(_('name'), max_length=255)
    host = models.CharField(_('server host'), max_length=255)
    user = models.CharField(_('server user'), max_length=128, blank=True,
                            help_text=_('Leave empty if the host is public.'))
    password = models.CharField(_('server password'), max_length=128, blank=True,
                                help_text=_('Leave empty if the host is public.'))
    port = models.IntegerField(_('server port'), default=25)
    tls = models.BooleanField(_('server use TLS'))

    headers = models.TextField(_('custom headers'), blank=True,
                               help_text=_('key1: value1 key2: value2, splitted by return line.\n'\
                                           'Useful for passing some tracking headers if your provider allows it.'))
    mails_hour = models.IntegerField(_('e-mail send rate'), help_text=_("E-Mail sending rate in messages per hour"),
                                     default=0)
    emails_remains = models.IntegerField(_('remaining e-mail'), help_text=_("Sendable E-Mail in the current account"),
                                         default=MAILER_HARD_LIMIT)

    def connect(self):
        """Connect the SMTP Server"""
        smtp = SMTP(smart_str(self.host), int(self.port))
        smtp.ehlo_or_helo_if_needed()
        if self.tls:
            smtp.starttls()
            smtp.ehlo_or_helo_if_needed()

        if self.user or self.password:
            smtp.login(smart_str(self.user), smart_str(self.password))
        return smtp

    def delay(self):
        """compute the delay (in seconds) between mails to ensure mails
        per hour limit is not reached

        :rtype: float
        """
        if not self.mails_hour:
            return 0.0
        else:
            return 3600.0 / self.mails_hour

    def credits(self):
        """Return how many mails the server can send"""
        if not self.mails_hour:
            return self.emails_remains

        last_hour = datetime.now() - timedelta(hours=1)
        sent_last_hour = ContactMailingStatus.objects.filter(
            models.Q(status=ContactMailingStatus.SENT) |
            models.Q(status=ContactMailingStatus.SENT_TEST),
            newsletter__server=self,
            creation_date__gte=last_hour).count()
        return self.mails_hour - sent_last_hour

    @property
    def custom_headers(self):
        if self.headers:
            headers = {}
            for header in self.headers.splitlines():
                if header:
                    key, value = header.split(':')
                    headers[key.strip()] = value.strip()
            return headers
        return {}

    def __unicode__(self):
        return '%s (%s)' % (self.name, self.host)

    class Meta:
        verbose_name = _('SMTP server')
        verbose_name_plural = _('SMTP servers')


class Contact(models.Model):
    """Contact for emailing"""
    email = models.EmailField(_('email'), unique=True)
    first_name = models.CharField(_('first name'), max_length=50, blank=True)
    last_name = models.CharField(_('last name'), max_length=50, blank=True)

    subscriber = models.BooleanField(_('subscriber'), default=True)
    valid = models.BooleanField(_('valid email'), default=True)
    tester = models.BooleanField(_('contact tester'), default=False)
    tags = TagField(_('tags'))

    content_type = models.ForeignKey(ContentType, blank=True, null=True)
    object_id = models.PositiveIntegerField(blank=True, null=True)
    content_object = generic.GenericForeignKey('content_type', 'object_id')

    creation_date = models.DateTimeField(_('creation date'), auto_now_add=True)
    modification_date = models.DateTimeField(_('modification date'), auto_now=True)

    objects = ContactManager()

    def subscriptions(self):
        """Return the user subscriptions"""
        return MailingList.objects.filter(subscribers=self)

    def unsubscriptions(self):
        """Return the user unsubscriptions"""
        return MailingList.objects.filter(unsubscribers=self)

    def vcard_format(self):
        return vcard_contact_export(self)

    def mail_format(self):
        if self.first_name and self.last_name:
            return '%s %s <%s>' % (self.last_name, self.first_name, self.email)
        return self.email
    mail_format.short_description = _('mail format')

    def get_absolute_url(self):
        if self.content_type and self.object_id:
            return self.content_object.get_absolute_url()
        return reverse('admin:newsletter_contact_change', args=(self.pk,))

    def __unicode__(self):
        if self.first_name and self.last_name:
            contact_name = '%s %s' % (self.last_name, self.first_name)
        else:
            contact_name = self.email
        if self.tags:
            return '%s | %s' % (contact_name, self.tags)
        return contact_name

    class Meta:
        ordering = ('creation_date',)
        verbose_name = _('contact')
        verbose_name_plural = _('contacts')


class MailingList(models.Model):
    """Mailing list"""
    name = models.CharField(_('name'), max_length=255)
    description = models.TextField(_('description'), blank=True)

    subscribers = models.ManyToManyField(Contact, verbose_name=_('subscribers'),
                                         related_name='mailinglist_subscriber')
    unsubscribers = models.ManyToManyField(Contact, verbose_name=_('unsubscribers'),
                                           related_name='mailinglist_unsubscriber',
                                           null=True, blank=True)

    creation_date = models.DateTimeField(_('creation date'), auto_now_add=True)
    modification_date = models.DateTimeField(_('modification date'), auto_now=True)

    def subscribers_count(self):
        return self.subscribers.all().count()
    subscribers_count.short_description = _('subscribers')

    def unsubscribers_count(self):
        return self.unsubscribers.all().count()
    unsubscribers_count.short_description = _('unsubscribers')

    def expedition_set(self):
        unsubscribers_id = self.unsubscribers.values_list('id', flat=True)
        return self.subscribers.valid_subscribers().exclude(
            id__in=unsubscribers_id)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('-creation_date',)
        verbose_name = _('mailing list')
        verbose_name_plural = _('mailing lists')


class Newsletter(models.Model):
    """Newsletter to be sended to contacts"""
    DRAFT = 0
    WAITING = 1
    SENDING = 2
    SENT = 4
    CANCELED = 5

    STATUS_CHOICES = ((DRAFT, _('draft')),
                      (WAITING, _('waiting sending')),
                      (SENDING, _('sending')),
                      (SENT, _('sent')),
                      (CANCELED, _('canceled')),
                      )

    title = models.CharField(_('title'), max_length=255,
                             help_text=_('You can use the "{{ UNIQUE_KEY }}" variable ' \
                                         'for unique identifier within the newsletter\'s title.'))
    content = models.TextField(_('content'), help_text=_('Or paste an URL.'),
                               default=_('<body>\n<!-- Edit your newsletter here -->\n</body>'))

    mailing_list = models.ForeignKey(MailingList, verbose_name=_('mailing list'))
    test_contacts = models.ManyToManyField(Contact, verbose_name=_('test contacts'),
                                           blank=True, null=True)

    server = models.ForeignKey(SMTPServer, verbose_name=_('smtp server'),
                               default=1)
    header_sender = models.CharField(_('sender'), max_length=255,
                                     default=DEFAULT_HEADER_SENDER)
    header_reply = models.CharField(_('reply to'), max_length=255,
                                    default=DEFAULT_HEADER_REPLY)

    status = models.IntegerField(_('status'), choices=STATUS_CHOICES, default=DRAFT)
    sending_date = models.DateTimeField(_('sending date'), default=datetime.now)

    slug = models.SlugField(help_text=_('Used for displaying the newsletter on the site.'),
                            unique=True)
    creation_date = models.DateTimeField(_('creation date'), auto_now_add=True)
    modification_date = models.DateTimeField(_('modification date'), auto_now=True)

    def mails_sent(self):
        return self.contactmailingstatus_set.filter(status=ContactMailingStatus.SENT).count()

djangocms_newsletter/views/newsletter.py
"""Views for emencia.django.newsletter Newsletter"""
from django.template import RequestContext
from django.shortcuts import get_object_or_404
from django.shortcuts import render_to_response

from django.contrib.sites.models import Site
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string as render_file

from emencia.django.newsletter.models import Newsletter
from emencia.django.newsletter.models import ContactMailingStatus
from emencia.django.newsletter.utils import render_string
from emencia.django.newsletter.utils.newsletter import body_insertion
from emencia.django.newsletter.utils.newsletter import track_links
from emencia.django.newsletter.utils.tokens import untokenize
from emencia.django.newsletter.settings import TRACKING_LINKS


def render_newsletter(request, slug, context):
    """Return a newsletter in HTML format"""
    newsletter = get_object_or_404(Newsletter, slug=slug)
    context.update({'newsletter': newsletter,
                    'domain': Site.objects.get_current().domain})

    content = render_string(newsletter.content, context)
    title = render_string(newsletter.title, context)
    if TRACKING_LINKS:
        content = track_links(content, context)
    unsubscription = render_file('newsletter/newsletter_link_unsubscribe.html', context)
    content = body_insertion(content, unsubscription, end=True)

    return render_to_response('newsletter/newsletter_detail.html',
                              {'content': content,
                               'title': title,
                               'object': newsletter},
                              context_instance=RequestContext(request))


@login_required
def view_newsletter_preview(request, slug):
    """View of the newsletter preview"""
    context = {'contact': request.user}
    return render_newsletter(request, slug, context)


def view_newsletter_contact(request, slug, uidb36, token):
    """Visualization of a newsletter by an user"""
    newsletter = get_object_or_404(Newsletter, slug=slug)
    contact = untokenize(uidb36, token)
    ContactMailingStatus.objects.create(newsletter=newsletter,
                                        contact=contact,
                                        status=ContactMailingStatus.OPENED_ON_SITE)
    context = {'contact': contact,
               'uidb36': uidb36, 'token': token}

    return render_newsletter(request, slug, context)

djangocms_newsletter/templates/newsletter/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xml:lang="{{ LANGUAGE_CODE }}" lang="{{ LANGUAGE_CODE }}" version="-//W3C//DTD XHTML 1.1//EN" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="language" content="{{ LANGUAGE_CODE }}" />
    <meta name="description" content="{% block meta-description %}Emencia Django Newsletter for sending newsletter.{% endblock %}" />
    <meta name="author" content="Fantomas42" />
    <title>Emencia Django Newsletter - {% block title %}{% endblock %}</title>
  </head>
  <body>
    <h1>Emencia Django Newsletter</h1>
    {% block content %}
    {% endblock %}
  </body>
</html>

djangocms_newsletter/templates/newsletter/contact_import.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
{% if not is_popup %}
<div class="breadcrumbs">
     <a href="../../../">{% trans "Home" %}</a> &rsaquo;
     <a href="../../">{{ app_label|capfirst|escape }}</a> &rsaquo;
     <a href="../">{{ opts.verbose_name_plural|capfirst }}</a> &rsaquo;
     {% trans 'Importation' %}
</div>
{% endif %}
{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}admin/css/forms.css" />{% endblock %}

{% block content %}
<div id="content-main">

  <form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
      <fieldset class="module aligned">
        <h2>{% trans "Excel" %}</h2>
        <div class="form-row source">
          <div>
            <label for="id_source" class="required">{% trans "Excel file (.xls)" %} :</label>
            <input name="type" value="excel" type="hidden" />
            <input name="source" id="id_source" type="file" class="vTextField" />
          </div>
          <p class="help">{% trans "Import contacts from a Excel file." %}<br />
            {% trans "Columns are [email][last name][first name][tags]." %}<br />
            {% trans "All columns are optionnal excepting the email." %}
          </p>
        </div>
      </fieldset>
      <div class="submit-row">
        <input type="submit" class="default" value="{% trans "Import" %}" />
      </div>
    </div>
  </form>

  <form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
      <fieldset class="module aligned">
        <h2>{% trans "Text" %}</h2>
        <div class="form-row source">
          <div>
            <label for="id_source" class="required">{% trans "Text file (.txt, .csv)" %} :</label>
            <input name="type" value="text" type="hidden" />
            <input name="source" id="id_source" type="file" class="vTextField" />
          </div>
          <p class="help">{% trans "Import contacts from a text file, or a CSV file." %}<br />
            {% trans "Columns are [email][last name][first name][tags], splitted by a dot coma." %}<br />
            {% trans "All columns are optionnal excepting the email." %}
          </p>
        </div>
      </fieldset>
      <div class="submit-row">
        <input type="submit" class="default" value="{% trans "Import" %}" />
      </div>
    </div>
  </form>

  <form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
      <fieldset class="module aligned">
        <h2>{% trans "VCard" %}</h2>
        <div class="form-row source">
          <div>
            <label for="id_source" class="required">{% trans "VCard file (.cvf)" %} :</label>
            <input name="type" value="vcard" type="hidden" />
            <input name="source" id="id_source" type="file" class="vTextField" />
          </div>
          <p class="help">{% trans "Import contacts from your favorite mail client, by providing a VCard file." %}</p>
        </div>
      </fieldset>
      <div class="submit-row">
        <input type="submit" class="default" value="{% trans "Import" %}" />
      </div>
    </div>
  </form>

  <form action="." method="post">
    {% csrf_token %}
    <div>
      <fieldset class="module aligned">
        <h2>{% trans "Raw text" %}</h2>
        <div class="form-row source">
          <div>
            <label for="id_source" class="required">{% trans "Raw text" %} :</label>
            <input name="type" value="text" type="hidden" />
            <textarea name="source" id="id_source" class="vLargeTextField" cols="40" rows="15" /></textarea>
          </div>
          <p class="help">{% trans "Columns are [email][last name][first name][tags], splitted by a dot coma." %}<br />
            {% trans "All columns are optionnal excepting the email." %}
          </p>
        </div>
      </fieldset>
      <div class="submit-row">
        <input type="submit" class="default" value="{% trans "Import" %}" />
      </div>
    </div>
  </form>

</div>
{% endblock %}

djangocms_newsletter/templates/newsletter/mailing_list_subscribe.html
{% extends "newsletter/base.html"%}
{% load i18n %}

{% block title %}{% trans "Subscription to mailing list" %}{% endblock %}

{% block content %}
  <h2>{% trans "Subscription to mailing list" %}</h2>

{% if subscribed %}
  <p>{% trans "Thanks for your subscription!" %}</p>
{% else %}
{% if mailing_list %}
  <h3>{{ mailing_list }}</h3>
  {{ mailing_list|linebreaks }}
{% else %}
  <p>{% trans "Validate this form to subscribe to the mailing lists." %}</p>
{% endif %}
  <form action="." method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans "Subscribe" %}" />
  </form>
{% endif %}

{% endblock %}

djangocms_newsletter/templates/newsletter/mailing_list_unsubscribe.html
{% extends "newsletter/base.html"%}
{% load i18n %}

{% block title %}{% trans "Unsubscription" %}{% endblock %}

{% block content %}
  <h2>{% trans "Unsubscription" %}</h2>
{% if already_unsubscribed %}
    {% if unsubscribed > 1 %}
        <p>{% trans "You are unsubscribed for all mailing lists." %}</p>
    {% else %}
        <p>{% trans "You are unsubscribed for this mailing list." %}</p>
    {% endif %}
{% else %}
  <p>{% trans "Validate this form to unsubscribe to this mailing list." %}</p>
  <form action="." method="post">
    {% csrf_token %}
    <input type="text" value="{{ email }}" name="email" readonly />
    <input type="submit" value="{% trans "Unsubscribe" %}" />
  </form>
{% endif %}
{% endblock %}

djangocms_newsletter/templates/newsletter/newsletter_detail.html
<html>
  <head>
    <title>{% block title %}{{ title }}{% endblock %}</title>
  </head>
  {% block body %}
    {{ content|safe }}
  {% endblock %}
</html>

djangocms_newsletter/templates/newsletter/newsletter_historic.html
{% extends "admin/change_list.html" %}
{% load i18n %}

{% block bodyclass %}change-list historic{% endblock %}

{% block breadcrumbs %}
{% if not is_popup %}
<div class="breadcrumbs">
     <a href="{% url admin:index %}">{% trans "Admin." %}</a> &rsaquo;
     <a href="{% url admin:app_list "newsletter" %}">{{ app_label|capfirst|escape }}</a> &rsaquo; 
     <a href="{% url admin:newsletter_newsletter_changelist %}">{{ opts.verbose_name_plural|capfirst }}</a> &rsaquo; 
     {{ title }}
</div>
{% endif %}
{% endblock %}

{% block content %}
<div id="content-main">
  <div class="module" id="changelist">
    <table cellspacing="0">
      <thead>
	<tr>
	  <th>{% trans "Date" %}</th>
	  <th>{% trans "Contact" %}</th>
	  <th>{% trans "Action" %}</th>
	</tr>
      </thead>
      <tbody>
	{% for event in original.contactmailingstatus_set.all %}
	<tr class="{% cycle row1,row2 %}">
	  <td class="nowrap">{{ event.creation_date|date:"d F Y, H:i" }}</td>
	  <td>{{ event.contact.mail_format }}</td>
	  <td>{{ event.get_status_display }} {% if event.link %}{{ event.link.url|urlize }}{% endif %}</td>
	</tr>
	{% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

djangocms_newsletter/templates/newsletter/newsletter_statistics.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}dashboard{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% load adminmedia %}{% admin_media_prefix %}css/dashboard.css" />{% endblock %}

{% block extrahead %}
<script type="text/javascript" src="{{ STATIC_URL }}edn/js/jquery.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}edn/js/jquery.form.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}edn/js/swfobject/swfobject.js"></script>
<script type="text/javascript">
OFC = {};

OFC.jquery = {
    name: "jQuery",
    version: function(src) { return $('#'+ src)[0].get_version() },
    rasterize: function (src, dst) { $('#'+ dst).replaceWith(OFC.jquery.image(src)) },
    image: function(src) { return "<img src='data:image/png;base64," + $('#'+src)[0].get_img_binary() + "' />"},
    popup: function(src) {
        var img_win = window.open('', 'Charts: Export as Image')
        with(img_win.document) {
            write('<html><head><title>Charts: Export as Image<\/title><\/head><bo' + 'dy>' + OFC.jquery.image(src) + '<\/body><\/html>') }
		  // stop the 'loading...' message
		  img_win.document.close();
     }
}

if (typeof(Control == "undefined")) {var Control = {OFC: OFC.jquery}}

function save_image() { OFC.jquery.popup('charts_view'); }

$(document).ready(function(){
  swfobject.embedSWF("{{ STATIC_URL }}edn/swf/open-flash-chart.swf", "charts_view", "498", "350", "9.0.0",
                     "{{ STATIC_URL }}edn/js/swfobject/expressInstall.swf",
                     {"data-file": "{% url newsletter_newsletter_charts object.slug %}"});

  function reload_charts(charts_data) {
    swfobject.getObjectById("charts_view").load(charts_data);
  };

  function validate(formData, jqForm, options) {
    for (var i=0; i < formData.length; i++) {
        if (formData[i].name == 'start') {
	  var start = parseInt(formData[i].value);
        }
        if (formData[i].name == 'end') {
	  var end = parseInt(formData[i].value);
        }
    }
    if (start > end) {
      return false;
    }
  };

  var options = {success: reload_charts,
                 beforeSubmit: validate};
  $("#period_selector").ajaxForm(options);
});
</script>
{% endblock %}

{% block breadcrumbs %}
{% if not is_popup %}
<div class="breadcrumbs">
     <a href="{% url admin:index %}">{% trans "Admin." %}</a> &rsaquo;
     <a href="{% url admin:app_list "newsletter" %}">{{ app_label|capfirst|escape }}</a> &rsaquo;
     <a href="{% url admin:newsletter_newsletter_changelist %}">{{ opts.verbose_name_plural|capfirst }}</a> &rsaquo;
     {{ title }}
</div>
{% endif %}
{% endblock %}

{% block content %}
<div id="content-main">
  {% if period %}
  <!-- Graph -->
  <div class="module" id="charts">
      <div id="charts_view"></div>
  </div>
  <div class="module" id="charts_options">
    <form id="period_selector" action="{% url newsletter_newsletter_charts object.slug %}" method="post">
      {% csrf_token %}
      <table summary="{% trans "Consultation histogram" %}">
	<tr>
	  <th scope="row" style="vertical-align: middle;">
	    {% trans "Period" %} :
	  </th>
	  <td>
	    <select name="start">
	      {% for date in period %}
	      <option value="{{ forloop.counter0 }}" {% ifequal forloop.counter0 0 %}selected="selected"{% endifequal %}>{{ date|date:"d M Y" }}</option>
	      {% endfor %}
	    </select>
	    <span>-></span>
	    <select name="end">
	      {% for date in period %}
	      <option value="{{ forloop.counter0 }}" {% ifequal forloop.counter0 6 %}selected="selected"{% endifequal %}>{{ date|date:"d M Y" }}</option>
	      {% endfor %}
	    </select>
	  </td>
	  <td><input type="submit" value="OK" /></td>
	</tr>
      </table>
    </form>
  </div>
  {% endif %}
  <!-- Receptions -->
  <div class="module" id="reception">
    <table summary="{% trans "Broadcasting statistics" %}">
      <caption><a href="#" class="section">{% trans "Broadcasting statistics" %}</a></caption>
      <tr>
        <th scope="row">{% trans "Total openings" %}</th>
	<td>&nbsp;</td>
        <td>{{ stats.total_openings }}</td>
      </tr>
      <tr>
        <th scope="row">{% trans "Openings on site" %}</th>
        <td>{{ stats.total_on_site_openings }}</td>
        <td>{{ stats.unique_on_site_openings }}</td>
      </tr>
      <tr>
        <th scope="row">{% trans "Total openings unique" %}</th>
        <td>{{ stats.unique_openings }}</td>
	<td>{{ stats.unique_openings_percent|floatformat:2 }}%</td>
      </tr>
      <tr>
        <th scope="row">{% trans "Unknow delivery" %}</th>
        <td>{{ stats.unknow_openings }}</td>
	<td>{{ stats.unknow_openings_percent|floatformat:2 }}%</td>
      </tr>
      <tr>
        <th scope="row">{% trans "Unsubscriptions" %}</th>
        <td>{{ stats.total_unsubscriptions }}</td>
	<td>{{ stats.total_unsubscriptions_percent|floatformat:2 }}%</td>
      </tr>
      <tr>
        <th scope="row">{% trans "Openings average" %}</th>
        <td>&nbsp;</td>
        <td>{{ stats.opening_average|floatformat:2 }}</td>
      </tr>
    </table>
  </div>
  <!-- Links -->
  <div class="module" id="reception">
    <table summary="{% trans "Links statistics" %}">
      <caption><a href="#" class="section">{% trans "Links statistics" %}</a></caption>
      <tr>
        <th scope="row">{% trans "Total clicked links" %}</th>
        <td>{{ stats.total_clicked_links }}</td>
        <td>{{ stats.total_clicked_links_percent|floatformat:2 }}%</td>
      </tr>
      <tr>
        <th scope="row">{% trans "Total clicked links unique" %}</th>
        <td>{{ stats.unique_clicked_links }}</td>
        <td>{{ stats.unique_clicked_links_percent|floatformat:2 }}%</td>
      </tr>
      <tr>
        <th scope="row">{% trans "Clicked links by openings" %}</th>
	<td>&nbsp;</td>
        <td>{{ stats.clicked_links_by_openings|floatformat:2 }}%</td>
      </tr>
      <tr>
        <th scope="row">{% trans "Clicked links average" %}</th>
	<td>&nbsp;</td>
        <td>{{ stats.clicked_links_average|floatformat:2 }}</td>
      </tr>
    </table>
  </div>
</div>
{% endblock %}

{% block sidebar %}
<div id="content-related">
    <div class="module" id="report-module">
      <h2>{% trans "Report" %}</h2>
      <h3>
	<a href="{% url newsletter_newsletter_report object.slug %}">{% trans "Download CSV report" %}</a>
      </h3>
      <p></p>
    </div>
    <div class="module" id="general-informations-module">
        <h2>{% trans "Informations" %}</h2>
	<h3>{% trans "Recipients" %}</h3>
	<p>{{ stats.mails_to_send }} <a href="{% url admin:newsletter_mailinglist_change object.mailing_list.pk %}">{% trans "View" %}</a></p>
        <h3>{% trans "Status" %}</h3>
	<p>{{ object.get_status_display }} {% if stats.remaining_mails %}<span class="mini quiet">(-{{ stats.remaining_mails }})</span>{% endif %}</p>
	<h3>{% trans "Sending date" %}</h3>
	<p>{{ object.sending_date|date:"d M Y H:i" }}</p>
	{% if stats.tests_sent %}
	<h3>{% trans "Tests sent" %}</h3>
	<p>{{ stats.tests_sent }}</p>
	{% endif %}
    </div>
    <div class="module" id="top-links-module">
	<h2>{% trans "Top Links" %}
	  (<a href="{% url newsletter_newsletter_density object.slug %}">{% trans "Density map" %}</a>)
	</h2>
	<ul class="actionlist">
	{% for top_link in stats.top_links %}
	<li><a href="{{ top_link.link.url }}" title="{{ top_link.link.title }}" target="blank">{{ top_link.link.title|slice:":23" }}</a>
	  <span class="quiet">({{ top_link.total_clicks }})</span>
	  <span class="mini quiet">({{ top_link.unique_clicks }})</span>
	</li>
	{% empty %}
	<li>{% trans "No Top Links yet." %}</li>
	{% endfor %}
	</ul>
    </div>
</div>
{% endblock %}